services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    tty: true
    volumes:
      - ..:/workspace:cached
      # - ~/.gitconfig:/root/.gitconfig:ro
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
